# Generated by Django 4.2.7 on 2023-11-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('background_info', models.TextField()),
                ('manifesto', models.TextField()),
                ('photo', models.ImageField(upload_to='Candidate/photo')),
            ],
        ),
    ]
