# Generated by Django 4.2.7 on 2023-12-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('P', 'President'), ('G', 'Governor'), ('S', 'Senator'), ('MP', 'Member of Parliament')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Polls.post'),
        ),
    ]
