# Generated by Django 4.2.7 on 2024-01-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0010_remove_vote_voter_vote_votes_alter_vote_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Polls.voter'),
        ),
    ]
