# Generated by Django 4.2.7 on 2024-01-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0013_vote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='Polls.post'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='votes',
        ),
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, to='Polls.vote'),
        ),
    ]
